---
abstract: 'Option parsing, done differently'
author:
  - 'Ryan P. Kelly <rpkelly@cpan.org>'
generated_by: 'Dist::Zilla version 1.093400'
license: mit
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Getopt-Flex
requires:
  Carp: 0
  Clone: 0
  File::Find::Rule: 0
  Image::ExifTool: 0
  Imager: 0
  Moose: 0
  Moose::Meta::TypeConstraint: 0
  Moose::Util::TypeConstraints: 0
  MooseX::StrictConstructor: 0
  Test::Exception: 0
  Test::More: 0
  Test::Warn: 0
  Time::Format: 0
version: 1.02
